/*
 * Material Management
 *
 * Materials API
 *
 * API version: 2.0
 * Contact: kenny.chen@iii.org.tw
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package middleware

import (
	"encoding/json"
	"material-management/db"
	"material-management/models"
	"net/http"
)

func LogPost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	var log models.MaterialLog
	err := json.NewDecoder(r.Body).Decode(&log)
	if err != nil {
		rDecodeErr(w, err)
		return
	}
	if err := db.InsertLog(log); err != nil {
		rLogicErr(w, err)
		return
	}
}

func LogsGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	logs, err := db.QueryLogs()
	if err != nil {
		rLogicErr(w, err)
		return
	}
	json.NewEncoder(w).Encode(logs)
}

func LatestLogsGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	maxTimestamp, err := db.QueryLogLastTime()
	if err != nil {
		rLogicErr(w, err)
		return
	}
	json.NewEncoder(w).Encode(maxTimestamp)

}
