/*
 * Material Management
 *
 * Materials API
 *
 * API version: 2.0
 * Contact: kenny.chen@iii.org.tw
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

import "fmt"

type Response struct {
	ID          int64  `json:"id,omitempty"`
	Message     string `json:"message,omitempty"`
	Description string `json:"description,omitempty"`
}

type SwaggerErr struct {
	Error_ string `json:"error,omitempty"`
}

type MyError struct {
	Message     string `json:"message"`
	Description string `json:"description"`
}

func (e MyError) Error() string {
	return fmt.Sprintf("%v: %v", e.Message, e.Description)
}
