/*
 * Material Management
 *
 * Materials API
 *
 * API version: 2.0
 * Contact: kenny.chen@iii.org.tw
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type Log struct {
	MaterialID   string `json:"material_id,omitempty"`
	MaterialName string `json:"material_name,omitempty"`
	TypeID       string `json:"type_id,omitempty"`
	TypeName     string `json:"type_name,omitempty"`
	InOrOut      string `json:"in_or_out,omitempty"`
	Timestamp    string `json:"timestamp,omitempty"`
	StaffID      string `json:"staff_id,omitempty"`
	StaffName    string `json:"staff_name,omitempty"`
	Quantity     int32  `json:"quantity,omitempty"`
	LogSn        int32  `json:"log_sn,omitempty"`
}

/*
INSERT INTO mes.inventory_log (material_id, material_name, type_id, type_name, in_or_out, quantity, staff_id, timestamp)
VALUES ('${material_id}', '${material_name}', '${type_id}', '${type_name}', '${in_or_out}', ${quantity}, '${staff_id}', NOW());

*/
