/*
 * Material Management
 *
 * Materials API
 *
 * API version: 2.0
 * Contact: kenny.chen@iii.org.tw
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type Material struct {
	MaterialID    string `json:"material_id,omitempty"`
	MaterialName  string `json:"material_name,omitempty"`
	TypeID        string `json:"type_id,omitempty"`
	TypeName      string `json:"type_name,omitempty"`
	StockLocation string `json:"stock_location,omitempty"`
	MinQty        int32  `json:"min_qty,omitempty"`
	Timestamp     string `json:"timestamp,omitempty"`
	TotalStock    int32  `json:"total_stock,omitempty"`
}

type UpdateMaterial struct {
	MaterialID    string `json:"material_id,omitempty"`
	MaterialName  string `json:"material_name,omitempty"`
	TypeID        string `json:"type_id,omitempty"`
	TypeName      string `json:"type_name,omitempty"`
	StockLocation string `json:"stock_location,omitempty"`
	MinQty        int32  `json:"min_qty,omitempty"`
	Timestamp     string `json:"timestamp,omitempty"`
	Quantity      int32  `json:"quantity,omitempty"`
}

//update material quantitiy request
type UpdateMaterialQuantity struct {
	Quantity int32 `json:"quantity,omitempty"`
}

//get materials request
type MaterialFilter struct {
	// Offset int64 `schema:"offset"`
	Limit  int64  `schema:"limit"`
	SortBy string `schema:"sortby"`
	Desc   bool   `schema:"desc"`
	Page   int64  `schema:"page"`

	//User specific filters
	MaterialID    string `schema:"material_id,omitempty"`
	MaterialName  string `schema:"material_name,omitempty"`
	TypeID        string `schema:"type_id,omitempty"`
	TypeName      string `schema:"type_name,omitempty"`
	StockLocation string `schema:"stock_location,omitempty"`
}
